#!/usr/bin/env python3


def gen_index(allmd):
    if len(allmd) > 10:
        s = 10
    else:
        s = len(allmd)
    selected = allmd[-s:]
    with open('index.md', 'w') as f:
        for post in reversed(selected):
            with open(post, 'r') as fn:
                name = post[:10]
                html = post.replace('.md', '.html')
                lines = fn.readlines()
                first = lines[0]
                f.write('<div class="post">')
                f.write('[<date>%s</date>](%s) %s' % (name, html, first))
                for line in lines[1:]:
                    f.write(line)
                f.write('</div>\n')


def gen_archive(allmd):
    with open('archive.md', 'w') as a:
        a.write('% All \n')
        a.write('% \n')
        a.write('% \n')
        for post in reversed(allmd):
            name = post[:10]
            with open(post, 'r') as fn:
                lines = fn.readlines()
                title = lines[0]
                html = post.replace('.md', '.html')
                a.write('[%s](%s) -- %s\n' % (name, html, title))


if __name__ == '__main__':
    import glob
    import sys
    allmd = glob.glob('2*.md')
    allmd.sort()
    if len(sys.argv) < 2:
        print('usage: ./bari archive|index')
        sys.exit(0)
    if sys.argv[1] == 'archive':
        gen_archive(allmd)
    if sys.argv[1] == 'index':
        gen_index(allmd)
